### PR TITLE
Encoding on file fixed

### PR DESCRIPTION
**Pull request by rmeertens**
Hey Rico, 

Today I had some problems with the encodings when running your code from a bash script.... For some reason it crashes with UTF-8 input. Running with PYTHONIOENCODING="UTF-8" and updating this line fixed it for me. Could you take a look at this?

### CODE REVIEW

**Comment by rsennrich** [comment]
Hi Roland,

thanks for the report. Unfortunately, it's quite a hassle to make this work consistently under python 2 and 3, and under different environment variables - your proposed fix breaks python 2.

**Comment by rmeertens** [comment]
Mmmm, too bad :(
What I could do is add an argument for the encoding... that would fix python 3 and would not break python 2.... Would that be a good idea?

**Comment by rsennrich** [comment]
I've pushed a possible fix as commit c82604. Feel free to test. If this works, the fix should also be applied to the other scripts.

**Comment by rmeertens** [comment]
Dear Rico, 

Sorry for my delayed response. I tried your fix a few days ago on some of my files, and it seems to work perfectly! Thank you very much for the fix!

**Comment by rsennrich** [comment]
This is now fixed in commits c8260 and 9f23b .

**Pull request closed without merging**
